// Rollup config for the vendored CodeMirror 6 bundle, following the setup in
// CodeMirror's own "Bundling with Rollup" guide.
//
// nodeResolve is what teaches Rollup to follow node-style specifiers such as
// "@codemirror/view" to node_modules/@codemirror/view/dist/index.js — CodeMirror
// ships as a graph of ES modules with bare imports, which no browser resolves on
// its own. terser is the size step the same guide recommends: the library is
// published with its full source, comments and whitespace included.
//
// The output is an IIFE with a single global, so index.html can load it with a
// plain <script> tag and app.js can read `CM` without any module plumbing.
import { nodeResolve } from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";

export default {
  input: "./cm6-entry.js",
  output: {
    file: "../web/vendor/codemirror.js",
    format: "iife",
    name: "CM",
    // The bundle is committed, so a stable byte-for-byte result matters more
    // than the few bytes a banner would cost: it keeps diffs to real changes.
    banner: "/* CodeMirror 6 — vendored bundle, generated by tools/. Do not edit. */",
  },
  plugins: [nodeResolve(), terser({ format: { comments: /^!|CodeMirror 6 — vendored/ } })],
};
