// Rollup config for the vendored CodeMirror 6 bundle, following the setup in
// CodeMirror's own "Bundling with Rollup" guide.
//
// nodeResolve is what teaches Rollup to follow node-style specifiers such as
// "@codemirror/view" to node_modules/@codemirror/view/dist/index.js — CodeMirror
// ships as a graph of ES modules with bare imports, which no browser resolves on
// its own. terser is the size step the same guide recommends: the library is
// published with its full source, comments and whitespace included.
//
// The output is an IIFE with a single global, so index.html can load it with a
// plain <script> tag and app.js can read `CM` without any module plumbing.
import { readFile, writeFile } from "node:fs/promises";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";
import postcss from "postcss";
import tailwindcss from "tailwindcss";
import cssnano from "cssnano";

// Rollup bundles JavaScript, so Tailwind cannot be an input to it the way the
// CodeMirror modules are — CSS never enters the module graph. What it can do is
// run in the same pass: this plugin drives Tailwind through PostCSS during the
// build and writes the stylesheet next to the JS bundle, so `rollup -c` still
// produces every vendored artifact in one command.
//
// It replaces the Play CDN (cdn.tailwindcss.com), which shipped 418 KB of
// JavaScript to compile the same CSS in the browser on every page load — a
// runtime network dependency in a tool whose whole point is working when the
// network is down.
function tailwind({ input, output }) {
  return {
    name: "tailwind",
    async writeBundle() {
      const css = await readFile(input, "utf8");
      const result = await postcss([
        tailwindcss({ config: "./tailwind.config.js" }),
        cssnano({ preset: "default" }),
      ]).process(css, { from: input, to: output });
      await writeFile(output, result.css);
      this.info(`tailwind -> ${output} (${(result.css.length / 1024).toFixed(0)} KB)`);
    },
  };
}

export default {
  input: "./cm6-entry.js",
  output: {
    file: "../web/vendor/codemirror.js",
    format: "iife",
    name: "CM",
    // The bundle is committed, so a stable byte-for-byte result matters more
    // than the few bytes a banner would cost: it keeps diffs to real changes.
    banner: "/* CodeMirror 6 — vendored bundle, generated by tools/. Do not edit. */",
  },
  plugins: [
    nodeResolve(),
    terser({ format: { comments: /^!|CodeMirror 6 — vendored/ } }),
    tailwind({ input: "./tailwind-input.css", output: "../web/vendor/tailwind.css" }),
  ],
};
