// Download the Material Symbols subset into web/vendor/fonts and emit fonts.css.
//
// Camer is a tool for repairing a reverse proxy, so it has to work on a host
// with no egress and while the proxy under repair is down. Anything fetched at
// runtime is a dependency that fails exactly when the tool is needed most.
//
// Body text is *not* vendored: index.html asks for the platform's own UI and
// monospace faces, so there is nothing to download and nothing to ship. Icons
// are the exception — they are ligatures in an icon font, and no operating
// system has one, so a glyph-less machine would render every button as the
// literal word "delete" or "close". This subset carries only the icons the UI
// actually uses.
//
// Run with `npm run fonts` from tools/; commit the result. Only needed when the
// icon set changes.
import { mkdir, readdir, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";

// Paths resolve against this file, not the shell's cwd, so the script can be
// run from either tools/ or the repo root.
const OUT = join(import.meta.dirname, "../web/vendor/fonts");

// A browser UA is what makes Google Fonts serve woff2 rather than ttf.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) " +
  "Chrome/126.0.0.0 Safari/537.36";

// Only the icons actually referenced by the UI: the full Material Symbols face
// is several megabytes, this subset is a few kilobytes.
const ICONS = `
add api arrow_forward block bolt check_circle close cloud_done cloud_download
cloud_off content_copy delete description dns edit_document error expand_more
help history history_toggle_off info keyboard keyboard_arrow_down
keyboard_arrow_up library_add menu refresh restore save search send sync
unfold_less unfold_more warning wrap_text
`
  .split(/\s+/)
  .filter(Boolean)
  .sort()
  .join(",");

const FACES = [
  [
    "symbols",
    "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" +
      "&icon_names=" +
      ICONS,
  ],
];

async function get(url, binary = false) {
  const res = await fetch(url, {
    headers: { "User-Agent": UA },
    signal: AbortSignal.timeout(60_000),
  });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return binary ? Buffer.from(await res.arrayBuffer()) : await res.text();
}

// Match on the declared format, not the extension: the icon-subset endpoint
// serves woff2 from a /l/font?kit=... URL with no suffix.
const SRC = /url\((https:\/\/[^)]+)\)\s*format\('([a-z0-9-]+)'\)/g;

await mkdir(OUT, { recursive: true });
const chunks = ["/* Generated by tools/vendor-fonts.mjs — do not edit by hand. */"];
const seen = new Map();
for (const [name, url] of FACES) {
  let css = await get(url);
  const found = [...new Set([...css.matchAll(SRC)].map((m) => `${m[1]}\t${m[2]}`))].sort();
  for (const entry of found) {
    const [src, fmt] = entry.split("\t");
    if (!seen.has(src)) {
      const fname = `${name}-${seen.size}.${fmt}`;
      await writeFile(join(OUT, fname), await get(src, true));
      seen.set(src, fname);
    }
    css = css.replaceAll(src, seen.get(src));
  }
  chunks.push(`/* ${name}: ${found.length} file(s) */\n` + css.trim());
  console.error(`${name}: ${found.length} woff2`);
}
await writeFile(join(OUT, "fonts.css"), chunks.join("\n\n") + "\n");

const sizes = await Promise.all(
  (await readdir(OUT)).map(async (f) => (await stat(join(OUT, f))).size),
);
const total = sizes.reduce((a, b) => a + b, 0);
console.error(
  `wrote ${OUT}/fonts.css and ${seen.size} font files (${Math.round(total / 1024)} KB)`,
);
