#!/usr/bin/env python3
"""Download the Material Symbols subset into web/vendor/fonts and emit fonts.css.

Camer is a tool for repairing a reverse proxy, so it has to work on a host with
no egress and while the proxy under repair is down. Anything fetched at runtime
is a dependency that fails exactly when the tool is needed most.

Body text is *not* vendored: index.html asks for the platform's own UI and
monospace faces, so there is nothing to download and nothing to ship. Icons are
the exception — they are ligatures in an icon font, and no operating system has
one, so a glyph-less machine would render every button as the literal word
"delete" or "close". This subset carries only the icons the UI actually uses.

Run from the repo root; commit the result. Only needed when the icon set changes.
"""
import os, re, sys, urllib.request

OUT = "web/vendor/fonts"
# A browser UA is what makes Google Fonts serve woff2 rather than ttf.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/126.0.0.0 Safari/537.36")

# Only the icons actually referenced by the UI: the full Material Symbols face is
# several megabytes, this subset is a few kilobytes.
ICONS = ",".join(sorted("""
add api arrow_forward block bolt check_circle close cloud_done cloud_download
cloud_off content_copy delete description dns edit_document error expand_more
help history history_toggle_off info keyboard keyboard_arrow_down
keyboard_arrow_up library_add menu refresh restore save search send sync
unfold_less unfold_more warning wrap_text
""".split()))

FACES = [
    ("symbols",  "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
                 "&icon_names=" + ICONS),
]

def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")

def main():
    os.makedirs(OUT, exist_ok=True)
    chunks = ["/* Generated by tools/vendor-fonts.py — do not edit by hand. */"]
    seen = {}
    for name, url in FACES:
        css = get(url)
        n = 0
        # Match on the declared format, not the extension: the icon-subset
        # endpoint serves woff2 from a /l/font?kit=... URL with no suffix.
        for src, fmt in sorted(set(re.findall(r"url\((https://[^)]+)\)\s*format\('([a-z0-9-]+)'\)", css))):
            if src not in seen:
                fname = f"{name}-{len(seen)}.{fmt}"
                open(os.path.join(OUT, fname), "wb").write(get(src, binary=True))
                seen[src] = fname
            css = css.replace(src, seen[src])
            n += 1
        chunks.append(f"/* {name}: {n} file(s) */\n" + css.strip())
        print(f"{name}: {n} woff2", file=sys.stderr)
    open(os.path.join(OUT, "fonts.css"), "w").write("\n\n".join(chunks) + "\n")
    total = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT))
    print(f"wrote {OUT}/fonts.css and {len(seen)} font files ({total/1024:.0f} KB)", file=sys.stderr)

main()
